# Generated by Django 3.0.5 on 2023-01-21 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20230121_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='persona',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='persona.Person'),
        ),
    ]
