# Generated by Django 3.0.5 on 2023-01-21 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_auto_20230121_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.Person'),
        ),
    ]
