# Generated by Django 4.1.4 on 2022-12-19 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_django", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin_modelo",
            options={
                "ordering": ["name"],
                "verbose_name": "Mi Departamento",
                "verbose_name_plural": "Areas de la empresa",
            },
        ),
        migrations.AlterUniqueTogether(
            name="admin_modelo",
            unique_together={("name", "shor_name")},
        ),
    ]
