# Generated by Django 4.1.4 on 2022-12-15 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departamentos", "0002_alter_departamento_shor_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firs_name", models.CharField(max_length=60, verbose_name="Nombres")),
                (
                    "last_name",
                    models.CharField(max_length=60, verbose_name="Apellidos"),
                ),
                (
                    "job",
                    models.CharField(
                        choices=[
                            (0, "Contador"),
                            (1, "Administrador"),
                            (2, "Economista"),
                            (3, "OTRO"),
                        ],
                        max_length=1,
                        verbose_name="Trabajo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departamentos.departamento",
                    ),
                ),
            ],
        ),
    ]
