# Generated by Django 4.1.4 on 2022-12-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="job",
            field=models.CharField(
                choices=[
                    ("0", "Contador"),
                    ("1", "Administrador"),
                    ("2", "Economista"),
                    ("3", "OTRO"),
                ],
                max_length=10,
                verbose_name="Trabajo",
            ),
        ),
    ]
