# Generated by Django 4.1.4 on 2022-12-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0003_alter_departamento_options_and_more"),
        ("empleados", "0002_alter_empleado_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilidades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "habilidad",
                    models.CharField(max_length=50, verbose_name="Habilidad"),
                ),
            ],
            options={
                "verbose_name": "Habilidad",
                "verbose_name_plural": "Habilidades de los Empleados",
            },
        ),
        migrations.RenameModel(
            old_name="Empleado",
            new_name="Empleados",
        ),
        migrations.AlterModelOptions(
            name="empleados",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Mi Empleado",
                "verbose_name_plural": "Empleados de la empresa",
            },
        ),
        migrations.RenameField(
            model_name="empleados",
            old_name="firs_name",
            new_name="first_name",
        ),
        migrations.AlterUniqueTogether(
            name="empleados",
            unique_together={("first_name", "departamento")},
        ),
    ]
