# Generated by Django 4.1.4 on 2023-01-13 00:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_empleados_avatar_empleados_habilidades"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleados",
            name="hoja_vida",
            field=ckeditor.fields.RichTextField(default="texto"),
            preserve_default=False,
        ),
    ]
