# Generated by Django 4.1.4 on 2023-01-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleados_hoja_vida'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Completo'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='job',
            field=models.CharField(choices=[('0', 'Contador'), ('1', 'Administrador'), ('2', 'Economista'), ('3', 'OTRO'), ('4', 'Gerente'), ('5', 'Operario')], max_length=10, verbose_name='Trabajo'),
        ),
    ]
