# Generated by Django 4.1.4 on 2022-12-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="shor_name",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Nombre Corto"
            ),
        ),
    ]
